# Generated by Django 2.1.3 on 2018-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-comment_time']},
        ),
        migrations.AddField(
            model_name='coment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
