# Generated by Django 2.1.3 on 2018-11-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181126_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Coment'),
        ),
    ]
