# Generated by Django 2.1.3 on 2018-11-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20181126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='comment.Coment'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='comment.Coment'),
        ),
    ]
